In [1]:
import torch

In [4]:
torch.empty(1)

tensor([10240.0049])

In [11]:
torch.zeros(2,3,2)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [16]:
x=torch.ones(2,2,2, dtype=torch.float16)

In [17]:
x.size()

torch.Size([2, 2, 2])

In [18]:
torch.tensor([.25,1.5])

tensor([0.2500, 1.5000])

In [19]:
x = torch.rand(2,2)
y = torch.rand(2,2)

z = x+y

In [20]:
z

tensor([[0.8657, 1.1202],
        [0.5971, 0.7190]])

In [21]:
y.add_(x)
y

tensor([[0.8657, 1.1202],
        [0.5971, 0.7190]])

In [23]:
z = x - y
z = torch.sub(x,y)

z = x*y
z = torch.mul(x,y)

In [24]:
x = torch.rand(5,3)

In [25]:
x

tensor([[0.7183, 0.9981, 0.5617],
        [0.4237, 0.9748, 0.5812],
        [0.9728, 0.8332, 0.4571],
        [0.7185, 0.7607, 0.4219],
        [0.7802, 0.7050, 0.6514]])

In [26]:
x[:,0]

tensor([0.7183, 0.4237, 0.9728, 0.7185, 0.7802])

In [27]:
x[1, :]

tensor([0.4237, 0.9748, 0.5812])

In [29]:
x.view(15)

tensor([0.7183, 0.9981, 0.5617, 0.4237, 0.9748, 0.5812, 0.9728, 0.8332, 0.4571,
        0.7185, 0.7607, 0.4219, 0.7802, 0.7050, 0.6514])

In [32]:
## autograd

x = torch.randn(3, requires_grad=True)
x

tensor([-1.1241,  0.3733,  1.3108], requires_grad=True)

In [34]:
y = x + 2
y

tensor([0.8759, 2.3733, 3.3108], grad_fn=<AddBackward0>)

In [35]:
z  = y*y*2
z

tensor([ 1.5344, 11.2656, 21.9226], grad_fn=<MulBackward0>)

In [36]:
z = z.mean()
z

tensor(11.5742, grad_fn=<MeanBackward0>)

In [37]:
z.backward()

In [38]:
x.grad

tensor([1.1679, 3.1645, 4.4144])

In [42]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights*3).sum()
    
    model_output.backward()
    
    print(weights.grad)
    
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [48]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)

w = torch.tensor(1.0, requires_grad=True)

In [49]:
# forward pass

y_hat = w*x

loss = (y_hat - y)**2


print(loss)

tensor(1., grad_fn=<PowBackward0>)


In [50]:
#backward pass

loss.backward()

print(w.grad)
# update our weights
# next forward And backward pass

tensor(-2.)
